### ISSUE TITLE
一部の難易度のみで画像を作りたい

### ISSUE THREAD

**Issue by KLAR-p** [Slime-hatena/FullCombo-management-tool-for-sl-stage#3]
いつも利用させていただき、ありがとうございます。
要望なのですが、現在のようにDEBUTからMASTER全てを表示するのではなく、
例えばMASTERだけ、PRO+MASTERのように、一部の難易度のみで画像を生成させたいです。
ご一考頂けますと幸いです。

**Comment by slime-hatena** [comment]
ご要望ありがとうございます。私も同じことを考えていたのですが、着手する時間が無かったので放置していました。
OrangeSapphireも終わりましたし、順番に手をつけてみようと思います。
どのぐらい時間がかかるかわかりませんが、実装をお待ちください。また何かありましたらお気軽にお書きください。

**Comment by slime-hatena** [comment]
ver151229で対応しました。
ぜひご利用ください。ご要望ありがとうございました。
